### ISSUE TITLE
关于编译

### ISSUE THREAD

**Issue by peng-yq** [kiqsont/tinyRPC#1]
您好，请问运行这个项目的环境以及需要装哪些库之类的呀？可以给出更详细的步骤吗，我看您README对于环境准备不够详细，如果可以，不甚感激。

**Comment by kiqsont** [comment]
安装好zookeeper和protobuf，可以从CMakeLists.txt中看到需要链接protobuf和zookeeper_mt两个库。同时还需要使用另外的tinyWebLib项目，需要在相关环境下编译出对应的库。如果不需要TLS功能，可以对tinyWebLib项目进行更改，这样就不需要在环境中准备OpenSSL对应的ssl和crypto。综上，最简单的编译方法是先下载或编译zookeeper和protobuf，然后进入tinyWebLib的replace设置成无需OpenSSL版本后编译tinyWebLib，最后对tinyRPC项目进行编译即可

**Comment by kiqsont** [comment]
> 您好，请问运行这个项目的环境以及需要装哪些库之类的呀？可以给出更详细的步骤吗，我看您README对于环境准备不够详细，如果可以，不甚感激。

安装好zookeeper和protobuf，可以从CMakeLists.txt中看到需要链接protobuf和zookeeper_mt两个库。同时还需要使用另外的tinyWebLib项目，需要在相关环境下编译出对应的库。如果不需要TLS功能，可以对tinyWebLib项目进行更改，这样就不需要在环境中准备OpenSSL对应的ssl和crypto。综上，最简单的编译方法是先下载或编译zookeeper和protobuf，然后进入tinyWebLib的replace设置成无需OpenSSL版本后编译tinyWebLib，最后对tinyRPC项目进行编译即可

**Comment by kiqsont** [comment]
抱歉这么晚才看到邮件。安装好zookeeper和protobuf，可以从CMakeLists.txt中看到需要链接protobuf和zookeeper_mt两个库。同时还需要使用另外的tinyWebLib项目，需要在相关环境下编译出对应的库。如果不需要TLS功能，可以对tinyWebLib项目进行更改，这样就不需要在环境中准备OpenSSL对应的ssl和crypto。综上，最简单的编译方法是先下载或编译zookeeper和protobuf，然后进入tinyWebLib的replace设置成无需OpenSSL版本后编译tinyWebLib，最后对tinyRPC项目进行编译即可




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kiqsont/tinyRPC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月17日(星期五) 下午4:18
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[kiqsont/tinyRPC] 关于编译 (Issue #1)





 
您好，请问运行这个项目的环境以及需要装哪些库之类的呀？可以给出更详细的步骤吗，我看您README对于环境准备不够详细，如果可以，不甚感激。

**Comment by kiqsont** [comment]
> 您好，请问运行这个项目的环境以及需要装哪些库之类的呀？可以给出更详细的步骤吗，我看您README对于环境准备不够详细，如果可以，不甚感激。

安装好zookeeper和protobuf，可以从CMakeLists.txt中看到需要链接protobuf和zookeeper_mt两个库。同时还需要使用另外的tinyWebLib项目，需要在相关环境下编译出对应的库可以从tinyWebLib/lib/目录下看到libasyncLogger.so与libtinyWebLib.so。如果不需要TLS功能，可以对tinyWebLib项目进行更改，这样就不需要在环境中准备OpenSSL对应的ssl和crypto。综上，最简单的编译方法是先下载或编译zookeeper和protobuf，然后进入tinyWebLib的replace设置成无需OpenSSL版本后编译tinyWebLib，最后对tinyRPC项目进行编译即可。后续会补出tinyWebLib库在该项目中的便捷使用方法。
